# CS4662 
## Group Project: Twitter Emotion Identification
### Instructor: Dr. Mohammad Porhomayoun

### Margarita Nuridjanian

Spring 2020

In [75]:
# import modules
import json
import pandas as pd
import numpy as np

In [76]:

# json_list = ['anger', 'fear', 'greed', 'hateful', 'joy', 'sadness']

# all_list = []
# limit = 10000

# for name in json_list:
#     # load json data as a list of strings
#     with open('raw_data/'+ name + '.json') as my_file:
#         myfile = json.load(my_file)
#         count = 0
        
#         # turn list to a list of tuples and append to all_list (only 10,000 from each list) 
#         for i in myfile:
#             if count < limit:
#                 all_list.append((i, name))
#                 count = count + 1
                
#             else:
#                 break
                
json_list = ['anger', 'fear', 'greed', 'hateful', 'joy', 'sadness']

all_list = []

for name in json_list:
    # load json data as a list of strings
    with open('raw_data/'+ name + '.json') as my_file:
        anger = json.load(my_file)
        
        # turn list to a list of tuples and append to all_list  
        for i in anger:
            all_list.append((i, name))
  

In [77]:
all_list[-1]

('Sad thing is sheep will buy into this POS https://t.co/hpeo1CSC70',
 'sadness')

In [78]:
# df = pd.DataFrame(np.array(list).reshape(-1,2), columns = ["comment", "emotion"])
df = pd.DataFrame(all_list, columns=['comment', 'label'])

In [79]:
# randomize the items inside dataframe
df = df.sample(frac=1)


In [80]:
df

comment    label
51669   Earning #cryptocurrency for selling my stuff o...     fear
64351   CoinNess prediction\nBTC price at the end of t...    greed
140566  This tweet, "#DAYTA #Blockchain #crypto https:...    greed
215251  @fesschain is Coming to Change the way How Peo...    greed
260701  @fiat_money @NationalDebt The consequences of ...  hateful
133565     XRP Likely to Outperform Bitcoin, There are...    greed
176224  Italy Targets 100 Mln in Blockchain &amp; Cryp...    greed
214841  Business Development Representative - MobLab (...    greed
116339  BitCherry Held A Launch Ceremony on the Global...    greed
162964  Senior Motion Capture Pipeline Technician - Ac...    greed
220089  Bullish Brits lost $34M to cryptocurrency scam...    greed
169100  CBSA exam dump: BTA Certified Blockchain Solut...    greed
13266   Crypto Panic: Heres Really Why Bitcoin Cash (B...     fear
268635  It was great to be part of the wonderful team ...      joy
87883   More than 20 US lawmakers once again urged the...    greed
232001  Stellar Climbs 10% As Investors Gain Confidenc...    greed
62457   #Blockchain - an undeniably impressive inventi...    greed
41806   Gibraltar Stock Exchange Integrates STGX Token...     fear
210103  Ethereum Price Gains Momentum Triggered By Bit...    greed
319215                      What if Elon is low key on CT  sadness
190705  BUY trade (ID #14998) for $TNT (Tierion) opene...    greed
292192  RT @bitseven: Cryptocurrency-leveraged trading...      joy
131223  Bitcoin Cash Is More Widely Accepted Than Bitc...    greed
135582  RT @cryptanalyser: #BTCUSD Market #1H timefram...    greed
185474  Wow! Another big event coming......Who wanna j...    greed
286339  Good luck in your balance; be wise with invest...      joy
255285  What is this cryptarded bullshit\n\nhttps://t....  hateful
239850  RT @startuprad_io: #Zurich-based @YAPEAL_CH is...    greed
45052   A Short History of Bitcoin, also known as elec...     fear
315833  RT @icoalert: While much has changed for us an...      joy
...                                                   ...      ...
188805  @lyssah_a My wife generally makes more money t...    greed
50330   Well, it was a nice pump and dump... lets hope...     fear
117570  Join Bitagro IEO ETH Competition. Get as many ...    greed
261260  @mybbpage Ugh me too I wish shed just come bac...  hateful
28957   Earning #cryptocurrency for selling my stuff o...     fear
17652   SIX, the Swiss national stock exchange group, ...     fear
320547  @realsheepwolf Add QB low floater $QPAG, 7.9 m...  sadness
295719  A very interesting idea! I'm sure it will be i...      joy
32134   #BTCUSD Market #1H timeframe on  May 6 at 00:0...     fear
262625  youre still some shit idk why youre happy , bu...  hateful
52129   Earning #cryptocurrency for selling my stuff o...     fear
5357    Earning #cryptocurrency for selling my stuff o...     fear
75979   Tennis Star Serena Williams Reveals Investment...    greed
269018   Great thread in addition https://t.co/oJh97tQYbC      joy
43293   By CCN: The Dow and broader U.S. stock market ...     fear
213536  "A long-term investment horizon" - Audrey Char...    greed
301091  after bloodbath 2018 people happy with 10-20% ...      joy
240248  A pump doesn't get more official than this \n\...    greed
13849   @pierre_rochard Nobody from Bitcoin community ...     fear
24764   Earning #cryptocurrency for selling my stuff o...     fear
37240   @Reecore_Coin to the moon. Within the week, $R...     fear
322295  RT @G_maker: Best pump coin ever is $BTT\n\n- ...  sadness
242397  BTT Looking very bullish! Follow my discord fo...    greed
242666  Update: cup and handle still in play, consolid...    greed
206667  And of course more #usecases.\n#blockchain #in...    greed
285452  IM SO HAPPY FOR MY COUSIN JIMMY\nhe deaf and h...      joy
250744  Given the already high-profile nature of Justi...    greed
104127  RT @atccofficial: Security Tips to Protect you...    greed
247359  Blockchain Is The Next

In [81]:
# from Hw4 #1 Data Science
from sklearn.model_selection import train_test_split

features = [feature for feature in df.columns.values[:-1]]
label = df.columns.values[-1]

X = df[features]  
y = df[label]

print(y)

51669        fear
64351       greed
140566      greed
215251      greed
260701    hateful
133565      greed
176224      greed
214841      greed
116339      greed
162964      greed
220089      greed
169100      greed
13266        fear
268635        joy
87883       greed
232001      greed
62457       greed
41806        fear
210103      greed
319215    sadness
190705      greed
292192        joy
131223      greed
135582      greed
185474      greed
286339        joy
255285    hateful
239850      greed
45052        fear
315833        joy
           ...   
188805      greed
50330        fear
117570      greed
261260    hateful
28957        fear
17652        fear
320547    sadness
295719        joy
32134        fear
262625    hateful
52129        fear
5357         fear
75979       greed
269018        joy
43293        fear
213536      greed
301091        joy
240248      greed
13849        fear
24764        fear
37240        fear
322295    sadness
242397      greed
242666      greed
206667    

In [82]:
X

comment
51669   Earning #cryptocurrency for selling my stuff o...
64351   CoinNess prediction\nBTC price at the end of t...
140566  This tweet, "#DAYTA #Blockchain #crypto https:...
215251  @fesschain is Coming to Change the way How Peo...
260701  @fiat_money @NationalDebt The consequences of ...
133565     XRP Likely to Outperform Bitcoin, There are...
176224  Italy Targets 100 Mln in Blockchain &amp; Cryp...
214841  Business Development Representative - MobLab (...
116339  BitCherry Held A Launch Ceremony on the Global...
162964  Senior Motion Capture Pipeline Technician - Ac...
220089  Bullish Brits lost $34M to cryptocurrency scam...
169100  CBSA exam dump: BTA Certified Blockchain Solut...
13266   Crypto Panic: Heres Really Why Bitcoin Cash (B...
268635  It was great to be part of the wonderful team ...
87883   More than 20 US lawmakers once again urged the...
232001  Stellar Climbs 10% As Investors Gain Confidenc...
62457   #Blockchain - an undeniably impressive inventi...
41806   Gibraltar Stock Exchange Integrates STGX Token...
210103  Ethereum Price Gains Momentum Triggered By Bit...
319215                      What if Elon is low key on CT
190705  BUY trade (ID #14998) for $TNT (Tierion) opene...
292192  RT @bitseven: Cryptocurrency-leveraged trading...
131223  Bitcoin Cash Is More Widely Accepted Than Bitc...
135582  RT @cryptanalyser: #BTCUSD Market #1H timefram...
185474  Wow! Another big event coming......Who wanna j...
286339  Good luck in your balance; be wise with invest...
255285  What is this cryptarded bullshit\n\nhttps://t....
239850  RT @startuprad_io: #Zurich-based @YAPEAL_CH is...
45052   A Short History of Bitcoin, also known as elec...
315833  RT @icoalert: While much has changed for us an...
...                                                   ...
188805  @lyssah_a My wife generally makes more money t...
50330   Well, it was a nice pump and dump... lets hope...
117570  Join Bitagro IEO ETH Competition. Get as many ...
261260  @mybbpage Ugh me too I wish shed just come bac...
28957   Earning #cryptocurrency for selling my stuff o...
17652   SIX, the Swiss national stock exchange group, ...
320547  @realsheepwolf Add QB low floater $QPAG, 7.9 m...
295719  A very interesting idea! I'm sure it will be i...
32134   #BTCUSD Market #1H timeframe on  May 6 at 00:0...
262625  youre still some shit idk why youre happy , bu...
52129   Earning #cryptocurrency for selling my stuff o...
5357    Earning #cryptocurrency for selling my stuff o...
75979   Tennis Star Serena Williams Reveals Investment...
269018   Great thread in addition https://t.co/oJh97tQYbC
43293   By CCN: The Dow and broader U.S. stock market ...
213536  "A long-term investment horizon" - Audrey Char...
301091  after bloodbath 2018 people happy with 10-20% ...
240248  A pump doesn't get more official than this \n\...
13849   @pierre_rochard Nobody from Bitcoin community ...
24764   Earning #cryptocurrency for selling my stuff o...
37240   @Reecore_Coin to the moon. Within the week, $R...
322295  RT @G_maker: Best pump coin ever is $BTT\n\n- ...
242397  BTT Looking very bullish! Follow my discord fo...
242666  Update: cup and handle still in play, consolid...
206667  And of course more #usecases.\n#blockchain #in...
285452  IM SO HAPPY FOR MY COUSIN JIMMY\nhe deaf and h...
250744  Given the already high-profile nature of Justi...
104127  RT @atccofficial: Security Tips to Protect you...
247359  Blockchain Is The Next Big Thing For Renewable...
16499   RT @xrptwin: #XRPCommunity #xrp\n\nMoney as in...

[328362 rows x 1 columns]

In [83]:
df = df.sample(frac=1).reset_index(drop=True)
df

comment  label
0       Gartner analyst @avivahl provides some perspec...  greed
1       Claim Free #Bitcoin Now? Link https://t.co/wWg...  greed
2       RT @Quark_Chain: Happy #InternationalWomensDay...    joy
3       Good Morning Twitter Fam.  Sending #steem love...    joy
4       Great News !!!! @hitbtc has allow withdrawals ...    joy
5       Cyptocurrency phones are a big potential leap ...  greed
6       Lol, fiat currencies only "unique selling poin...   fear
7       Something happy to start your weekend.\nBlockc...    joy
8       Samsung designing 3nm and 5nm BTC mining chips...  greed
9       I hate no idea that Joe Jonas was pitching for...  anger
10      Markets Dump $30 Billion In Massive Crypto Cor...   fear
11      @CryptoCobain I've got kids. That's a great de...    joy
12      RT @CoinCodex: As the #cryptocurrency market a...  greed
13      #Cryptocurrency and #blockchain news by @CoinN...  greed
14      At the beginning of 2018, Bitcoin stood at mor...  greed
15      More\nOur airdrop snapshot will happen on 15th...  greed
16      RT @Blox_Official: More and more Fortune100s a...  greed
17      @Anggrek49625707 @atikafadiyah @MBLAQSH @Zenda...  greed
18      good project and will go to moon   #blockchain...  greed
19      RT @SteveYeagerNV: Great day on the floor of t...  greed
20      RT @Shewsyy:  ALTCOINS \n\nWhat hot altcoins d...  greed
21       Revolutionary Solutions for #Medical Field Us...  greed
22      Earning #cryptocurrency for selling my stuff o...   fear
23      Bitcoin [BTC] and Litecoin [LTC] Price Analysi...  greed
24      Environmental Compliance Training Manager - 7 ...  greed
25      #Bitcoin Expecting for completion of B correct...  greed
26      The future is bright and clear... So moonly fo...    joy
27      Short-Term Bitcoin Bear: HODLers To Be Decimat...   fear
28      Operations Intern - Danone North America ( Cit...  greed
29      Earning #cryptocurrency for selling my stuff o...   fear
...                                                   ...    ...
328332  The Real Stark Industries https://t.co/lqGie2A...  greed
328333   \n\nHave you lost your hard earned money to; ...  greed
328334  Earning #cryptocurrency for selling my stuff o...   fear
328335  CIO @TheresaSzczurek is tackling big projects ...  greed
328336  The latest @joerogan with @adamconover is fuck...    joy
328337  #HIGH #HighBank #ICO #Bitcoin #Ethereum #Crypt...    joy
328338  Fullstack Java/Web #Developer. - Hays Finance ...  greed
328339  Information Security Engineer - TribolaTech In...  greed
328340  Can admin post tweets? Share them here. Maby i...  greed
328341  RT @Crypto__Project: Welcome @Runebase_Tweet a...    joy
328342  Bitfury, Swiss Investment Firm Launch Regulate...  greed
328343  Great Growth For Bitcoin After A Long Time! Ma...    joy
328344  Great solutions to global problems at #thinkAU...    joy
328345  Bitcoin Futures Are More Significant Than We T...  greed
328346  RT @L1saR_: @Masternode_Buzz @RapidsRPD @Coino...  greed
328347  I think they meant to say, and it's getting be...  greed
328348  @cfbiz \nKrushia is a series of animated movie...  greed
328349  #AMANPURIExchange managed to create a system f...  greed
328350  Investing Tips from a Pro\n\n https://t.co/S9G...   fear
328351  @canyacoin great work @canyacoin pump fiat mon...  greed
328352  The traditional investment landscape does not ...  greed
328353  #KuCoin is extremely proud to announce yet ano...    joy
328354  MXC Added YST/USDT &amp; ADA/USDT Trading pair...  greed
328355  London Stock Exchange CEO Is Certain That Bloc...   fear
328356  The MYPAY blockchain bank landed and appeared ...  greed
328357  RT @Vertalo_: Column: Its About Time for Stock...   fear
328358  RT @silvertoe123: DOGE - 1 Mission to the Moon...  greed
328359  ancient Chinese money, shaped like spades, had...  greed
328360  Specialist, Manufacturing Compliance - Merial ...  greed
328361  Earning #cryptocurrency for selling my stuff o...   fear

[328362 rows x 2 co

In [84]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [85]:
# Splitting the dataset into testing and training:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, 
                                                    random_state=3)

In [86]:
# X_train = df['comment']
X_train['comment']

126377    Denzel coin \nICO ROUND 3\nSmart contract addr...
53912      Born and Raised - John Mayer\n Where the Ligh...
188857    Blockchain Real Estate Startups Shaking Up Pro...
52958     Earning #cryptocurrency for selling my stuff o...
310484    We are happy to be sharing you some of week-18...
207439    Bitcoin Hash Rate Hits New All-Time-High https...
256486    Nuh uh, Teresa Mendoza showed me not to fw peo...
184607    RT @halal_crypto: Is bitcoin on the verge of a...
257427    @soffenbaker That jog to the foul line looked ...
289882    We're happy to announce bitcoinone will be add...
239683    #StandWith @realDonaldTrump  @RepAdamSchiff  i...
316478    I can already tell this is gonna be a great, I...
110217    This may help legalise cryptocurrency in India...
193360    Project Manager - TV &amp; Radio - BBC ( Salfo...
301671    RT @BlockSafeTech: While its great to see #Blo...
323140    Hey #LitecoinFam Low fee #LTC and #BTC ATM on ...
311734    Among all the great news in th

In [87]:
X_test['comment']

2243      BTC haters gonna hate no matter what... this e...
194182    Now Hiring Front Of House Positions - The Crac...
201800    @justinsuntron Beside profit(game,gambling,cas...
52730     Earning #cryptocurrency for selling my stuff o...
45693     Earning #cryptocurrency for selling my stuff o...
232865    The more picket lines and union members #JoeBi...
147030    MiracleTele is the worlds first fully operatio...
194441    Fuck the moon we're leaving the milky way in 2...
318679    Join the New Perspective Cryptocurrency Exchan...
142104    @Bitbond variable coupon is based on the inves...
105536    RT @LiveTreeHQ: This is big news. Are you guys...
166956    This Blockchain Executive Is Advocating For Mo...
149913    https://t.co/gVoZbWFRSW\n\n**** If you are alr...
45102     Earning #cryptocurrency for selling my stuff o...
243437    Evening all, heres a longer more in-depth read...
149686    Many of these upgrades also make the trading p...
16330     25,000 BTC Moved Before Yester

In [88]:
# y_train = df['comment']

In [89]:
# Print first 5 rows
df.head()
# X_train = train_df['text']
# y_train = train_df['author']
# X_test = test_df['text']
vectorizer = CountVectorizer()

In [90]:
corpus = pd.concat([X_train['comment'], X_test['comment']])
vectorizer.fit(corpus)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [91]:
corpus

126377    Denzel coin \nICO ROUND 3\nSmart contract addr...
53912      Born and Raised - John Mayer\n Where the Ligh...
188857    Blockchain Real Estate Startups Shaking Up Pro...
52958     Earning #cryptocurrency for selling my stuff o...
310484    We are happy to be sharing you some of week-18...
207439    Bitcoin Hash Rate Hits New All-Time-High https...
256486    Nuh uh, Teresa Mendoza showed me not to fw peo...
184607    RT @halal_crypto: Is bitcoin on the verge of a...
257427    @soffenbaker That jog to the foul line looked ...
289882    We're happy to announce bitcoinone will be add...
239683    #StandWith @realDonaldTrump  @RepAdamSchiff  i...
316478    I can already tell this is gonna be a great, I...
110217    This may help legalise cryptocurrency in India...
193360    Project Manager - TV &amp; Radio - BBC ( Salfo...
301671    RT @BlockSafeTech: While its great to see #Blo...
323140    Hey #LitecoinFam Low fee #LTC and #BTC ATM on ...
311734    Among all the great news in th

In [92]:
X_train['comment']

126377    Denzel coin \nICO ROUND 3\nSmart contract addr...
53912      Born and Raised - John Mayer\n Where the Ligh...
188857    Blockchain Real Estate Startups Shaking Up Pro...
52958     Earning #cryptocurrency for selling my stuff o...
310484    We are happy to be sharing you some of week-18...
207439    Bitcoin Hash Rate Hits New All-Time-High https...
256486    Nuh uh, Teresa Mendoza showed me not to fw peo...
184607    RT @halal_crypto: Is bitcoin on the verge of a...
257427    @soffenbaker That jog to the foul line looked ...
289882    We're happy to announce bitcoinone will be add...
239683    #StandWith @realDonaldTrump  @RepAdamSchiff  i...
316478    I can already tell this is gonna be a great, I...
110217    This may help legalise cryptocurrency in India...
193360    Project Manager - TV &amp; Radio - BBC ( Salfo...
301671    RT @BlockSafeTech: While its great to see #Blo...
323140    Hey #LitecoinFam Low fee #LTC and #BTC ATM on ...
311734    Among all the great news in th

In [93]:
from sklearn.tree import DecisionTreeClassifier

my_DecisionTree = DecisionTreeClassifier(random_state=2)


In [94]:
# Find unique value counts of each author
y_train.value_counts()

greed      130014
joy         35620
fear        32446
hateful      6689
sadness      6331
anger        2335
Name: label, dtype: int64

In [95]:
X_tr_new = vectorizer.transform(X_train['comment'])

In [96]:
my_DecisionTree.fit(X_tr_new, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=2, splitter='best')

In [97]:
X_tt_new = vectorizer.transform(X_test['comment'])

In [98]:
# X.value_count()

In [99]:
# Predicting the Binary Label:
y_predict_lr = my_DecisionTree.predict(X_tt_new)
print(y_predict_lr)

['hateful' 'greed' 'greed' ... 'greed' 'greed' 'greed']


In [100]:
# Estimating the probability (likelihood) of Each Label: 
y_pred_proba_lr = my_DecisionTree.predict_proba(X_tt_new)
y_pred_proba_lr

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [101]:
# Find accuracy score
score_lr = accuracy_score(y_test, y_predict_lr)
print("Decision tree accuracy:", score_lr)

Decision tree accuracy: 0.9249697634150373


In [102]:
#from Hw4 #1 bagging method


from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.utils import resample

X_train_Sample_size = int(0.8*len(X_train))
Base_DecisionTree = DecisionTreeClassifier(random_state=2)


# predictions = []

predictions = pd.DataFrame()


In [103]:
for i in range(3):
    X_train_i = resample(X_tr_new, n_samples = X_train_Sample_size , random_state=i , replace = True)
    y_train_i = resample(y_train, n_samples = X_train_Sample_size , random_state=i , replace = True)
    Base_DecisionTree.fit(X_train_i, y_train_i)
    predictions[i] = Base_DecisionTree.predict(X_tt_new)
#     y_predict = Base_DecisionTree.predict(X_test)
#     accuracy = accuracy_score(y_test, y_predict)
#     predictions.append(accuracy)
    
# print(predictions)

In [104]:
y_2 = predictions.mode(axis=1)


In [105]:
y_test

2243        anger
194182      greed
201800      greed
52730        fear
45693        fear
232865      greed
147030      greed
194441      greed
318679    sadness
142104      greed
105536      greed
166956      greed
149913      greed
45102        fear
243437      greed
149686      greed
16330        fear
158479      greed
145976      greed
212703      greed
104986      greed
181940      greed
216324      greed
173221      greed
227258      greed
222026      greed
235218      greed
64575       greed
289831        joy
227257      greed
           ...   
88212       greed
38924        fear
286365        joy
196290      greed
300684        joy
235014      greed
68559       greed
205448      greed
48605        fear
226407      greed
43115        fear
247809      greed
19710        fear
231068      greed
199171      greed
65113       greed
197147      greed
258494    hateful
275731        joy
61656       greed
122578      greed
10010        fear
213636      greed
199193      greed
152239    

In [106]:
y_2 = predictions.mode(axis=1)

In [107]:
predictions

0        1        2
0         anger    greed  hateful
1         greed    greed    greed
2         greed    greed    greed
3          fear     fear     fear
4          fear     fear     fear
5         greed    greed    greed
6         greed    greed    greed
7         greed    greed    greed
8       sadness  sadness  sadness
9         greed    greed    greed
10          joy    greed      joy
11        greed    greed    greed
12        greed    greed    greed
13         fear     fear     fear
14        greed    greed    greed
15        greed    greed    greed
16        greed     fear    greed
17        greed    greed    greed
18        greed    greed    greed
19        greed    greed    greed
20        greed    greed    greed
21        greed    greed    greed
22        greed    greed    greed
23        greed    greed    greed
24        greed    greed    greed
25        greed    greed    greed
26        greed    greed    greed
27        greed    greed    greed
28          joy      joy      joy
29        greed    greed    greed
...         ...      ...      ...
114897    greed    greed    greed
114898     fear     fear     fear
114899      joy      joy      joy
114900    greed    greed    greed
114901      joy      joy      joy
114902    greed    greed    greed
114903    greed    greed    greed
114904    greed    greed    greed
114905     fear     fear     fear
114906    greed    greed    greed
114907     fear     fear     fear
114908    greed    greed    greed
114909     fear     fear     fear
114910    greed    greed    greed
114911    greed    greed    greed
114912    greed    greed    greed
114913    greed    greed    greed
114914  hateful  hateful  hateful
114915      joy      joy      joy
114916    greed    greed    greed
114917    greed    greed    greed
114918    greed    greed    greed
114919    greed    greed    greed
114920    greed    greed    greed
114921    greed    greed    greed
114922    greed    greed    greed
114923    greed      joy      joy
114924    greed    greed    greed
114925    greed    greed    greed
114926    greed    greed    greed

[114927 rows x 3 columns]

In [108]:
y_2[0]

0           anger
1           greed
2           greed
3            fear
4            fear
5           greed
6           greed
7           greed
8         sadness
9           greed
10            joy
11          greed
12          greed
13           fear
14          greed
15          greed
16          greed
17          greed
18          greed
19          greed
20          greed
21          greed
22          greed
23          greed
24          greed
25          greed
26          greed
27          greed
28            joy
29          greed
           ...   
114897      greed
114898       fear
114899        joy
114900      greed
114901        joy
114902      greed
114903      greed
114904      greed
114905       fear
114906      greed
114907       fear
114908      greed
114909       fear
114910      greed
114911      greed
114912      greed
114913      greed
114914    hateful
114915        joy
114916      greed
114917      greed
114918      greed
114919      greed
114920      greed
114921    

In [109]:
accuracy = accuracy_score(y_test, y_2[0])
print("Final accuracy of bagging voting method is: ", accuracy)

Final accuracy of bagging voting method is:  0.9331488684121225


In [110]:
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_test, y_predict_lr))
cm = confusion_matrix(y_test, y_predict_lr)
print(cm)

              precision    recall  f1-score   support

       anger       0.50      0.56      0.53      1261
        fear       0.89      0.92      0.90     17607
       greed       0.95      0.95      0.95     70163
     hateful       0.79      0.75      0.77      3517
         joy       0.93      0.91      0.92     18945
     sadness       0.83      0.77      0.80      3434

    accuracy                           0.92    114927
   macro avg       0.81      0.81      0.81    114927
weighted avg       0.93      0.92      0.93    114927

[[  705    28    61   447    15     5]
 [   32 16124  1243    46   107    55]
 [   88  1640 66854   175  1019   387]
 [  544    67   215  2639    37    15]
 [   22   162  1316    33 17321    91]
 [   14   100   508    19   132  2661]]


In [111]:
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_test, y_2[0]))
cm = confusion_matrix(y_test, y_2[0])
print(cm)

              precision    recall  f1-score   support

       anger       0.57      0.59      0.58      1261
        fear       0.91      0.92      0.91     17607
       greed       0.96      0.96      0.96     70163
     hateful       0.80      0.79      0.80      3517
         joy       0.93      0.93      0.93     18945
     sadness       0.83      0.82      0.82      3434

    accuracy                           0.93    114927
   macro avg       0.83      0.83      0.83    114927
weighted avg       0.93      0.93      0.93    114927

[[  738    20    54   424    19     6]
 [   20 16194  1164    46   124    59]
 [   74  1415 67088   178  1020   388]
 [  446    53   168  2787    43    20]
 [   14   104  1067    32 17628   100]
 [   10    78   426    15    96  2809]]
